# for xilinx_u280_xdma_201920_3

# (c) Copyright 2017, 2019 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
############################################################
#
# *************************************************************************

set_property IOSTANDARD LVDS [get_ports c0_sys_clk_p]
set_property IOSTANDARD LVDS [get_ports c0_sys_clk_n]
set_property IOSTANDARD LVDS [get_ports c1_sys_clk_p]
set_property IOSTANDARD LVDS [get_ports c1_sys_clk_n]
set_property IOSTANDARD LVDS [get_ports xmc_clk_clk_p]
set_property IOSTANDARD LVDS [get_ports xmc_clk_clk_n]
set_property DQS_BIAS TRUE [get_ports c0_sys_clk_p]
set_property DQS_BIAS TRUE [get_ports c0_sys_clk_n]
set_property DQS_BIAS TRUE [get_ports c1_sys_clk_p]
set_property DQS_BIAS TRUE [get_ports c1_sys_clk_n]
set_property DQS_BIAS TRUE [get_ports xmc_clk_clk_p]
set_property DQS_BIAS TRUE [get_ports xmc_clk_clk_n]


# False path on data and kernel Reset
set_false_path -through [get_pins -hier -regexp .*mss_0/inst/hbm_inst/inst/.*_STACK.*/AXI_.*_ARESET_N.*]

# Lock down "unused" package pins...board flow does not seem to be taken into account for "hanging" pins..
set_property PACKAGE_PIN L49 [get_ports {io_gt_gtyquad_00_gtx_n[0]}]
set_property PACKAGE_PIN L48 [get_ports {io_gt_gtyquad_00_gtx_p[0]}]
set_property PACKAGE_PIN L54 [get_ports {io_gt_gtyquad_00_grx_n[0]}]
set_property PACKAGE_PIN L53 [get_ports {io_gt_gtyquad_00_grx_p[0]}]
set_property PACKAGE_PIN L45 [get_ports {io_gt_gtyquad_00_gtx_n[1]}]
set_property PACKAGE_PIN L44 [get_ports {io_gt_gtyquad_00_gtx_p[1]}]
set_property PACKAGE_PIN K52 [get_ports {io_gt_gtyquad_00_grx_n[1]}]
set_property PACKAGE_PIN K51 [get_ports {io_gt_gtyquad_00_grx_p[1]}]
set_property PACKAGE_PIN K47 [get_ports {io_gt_gtyquad_00_gtx_n[2]}]
set_property PACKAGE_PIN K46 [get_ports {io_gt_gtyquad_00_gtx_p[2]}]
set_property PACKAGE_PIN J54 [get_ports {io_gt_gtyquad_00_grx_n[2]}]
set_property PACKAGE_PIN J53 [get_ports {io_gt_gtyquad_00_grx_p[2]}]
set_property PACKAGE_PIN J49 [get_ports {io_gt_gtyquad_00_gtx_n[3]}]
set_property PACKAGE_PIN J48 [get_ports {io_gt_gtyquad_00_gtx_p[3]}]
set_property PACKAGE_PIN H52 [get_ports {io_gt_gtyquad_00_grx_n[3]}]
set_property PACKAGE_PIN H51 [get_ports {io_gt_gtyquad_00_grx_p[3]}]
set_property PACKAGE_PIN G49 [get_ports {io_gt_gtyquad_01_gtx_n[0]}]
set_property PACKAGE_PIN G48 [get_ports {io_gt_gtyquad_01_gtx_p[0]}]
set_property PACKAGE_PIN G54 [get_ports {io_gt_gtyquad_01_grx_n[0]}]
set_property PACKAGE_PIN G53 [get_ports {io_gt_gtyquad_01_grx_p[0]}]
set_property PACKAGE_PIN E49 [get_ports {io_gt_gtyquad_01_gtx_n[1]}]
set_property PACKAGE_PIN E48 [get_ports {io_gt_gtyquad_01_gtx_p[1]}]
set_property PACKAGE_PIN F52 [get_ports {io_gt_gtyquad_01_grx_n[1]}]
set_property PACKAGE_PIN F51 [get_ports {io_gt_gtyquad_01_grx_p[1]}]
set_property PACKAGE_PIN C49 [get_ports {io_gt_gtyquad_01_gtx_n[2]}]
set_property PACKAGE_PIN C48 [get_ports {io_gt_gtyquad_01_gtx_p[2]}]
set_property PACKAGE_PIN E54 [get_ports {io_gt_gtyquad_01_grx_n[2]}]
set_property PACKAGE_PIN E53 [get_ports {io_gt_gtyquad_01_grx_p[2]}]
set_property PACKAGE_PIN A50 [get_ports {io_gt_gtyquad_01_gtx_n[3]}]
set_property PACKAGE_PIN A49 [get_ports {io_gt_gtyquad_01_gtx_p[3]}]
set_property PACKAGE_PIN D52 [get_ports {io_gt_gtyquad_01_grx_n[3]}]
set_property PACKAGE_PIN D51 [get_ports {io_gt_gtyquad_01_grx_p[3]}]
set_property PACKAGE_PIN T43 [get_ports {io_clk_gtyquad_refclk0_00_clk_n}]
set_property PACKAGE_PIN T42 [get_ports {io_clk_gtyquad_refclk0_00_clk_p}]
set_property PACKAGE_PIN R41 [get_ports {io_clk_gtyquad_refclk1_00_clk_n}]
set_property PACKAGE_PIN R40 [get_ports {io_clk_gtyquad_refclk1_00_clk_p}]
set_property PACKAGE_PIN P43 [get_ports {io_clk_gtyquad_refclk0_01_clk_n}]
set_property PACKAGE_PIN P42 [get_ports {io_clk_gtyquad_refclk0_01_clk_p}]
set_property PACKAGE_PIN M43 [get_ports {io_clk_gtyquad_refclk1_01_clk_n}]
set_property PACKAGE_PIN M42 [get_ports {io_clk_gtyquad_refclk1_01_clk_p}]

# Have to add package pin constraints for DDRs when prohibits are in place
# Have to place all DDR pins as with prohinits it becomes a problem otherwise
set_property PACKAGE_PIN BH41 [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN BF46 [get_ports c0_ddr4_adr[0]]
set_property PACKAGE_PIN BG43 [get_ports c0_ddr4_adr[1]]
set_property PACKAGE_PIN BK45 [get_ports c0_ddr4_adr[2]]
set_property PACKAGE_PIN BF42 [get_ports c0_ddr4_adr[3]]
set_property PACKAGE_PIN BL45 [get_ports c0_ddr4_adr[4]]
set_property PACKAGE_PIN BF43 [get_ports c0_ddr4_adr[5]]
set_property PACKAGE_PIN BG42 [get_ports c0_ddr4_adr[6]]
set_property PACKAGE_PIN BL43 [get_ports c0_ddr4_adr[7]]
set_property PACKAGE_PIN BK43 [get_ports c0_ddr4_adr[8]]
set_property PACKAGE_PIN BM42 [get_ports c0_ddr4_adr[9]]
set_property PACKAGE_PIN BG45 [get_ports c0_ddr4_adr[10]]
set_property PACKAGE_PIN BD41 [get_ports c0_ddr4_adr[11]]
set_property PACKAGE_PIN BL42 [get_ports c0_ddr4_adr[12]]
set_property PACKAGE_PIN BE44 [get_ports c0_ddr4_adr[13]]
set_property PACKAGE_PIN BE43 [get_ports c0_ddr4_adr[14]]
set_property PACKAGE_PIN BL46 [get_ports c0_ddr4_adr[15]]
set_property PACKAGE_PIN BH44 [get_ports c0_ddr4_adr[16]]
set_property PACKAGE_PIN BH45 [get_ports c0_ddr4_ba[0]]
set_property PACKAGE_PIN BM47 [get_ports c0_ddr4_ba[1]]
set_property PACKAGE_PIN BF41 [get_ports c0_ddr4_bg[0]]
set_property PACKAGE_PIN BE41 [get_ports c0_ddr4_bg[1]]
set_property PACKAGE_PIN BJ46 [get_ports c0_ddr4_ck_c[0]]
set_property PACKAGE_PIN BH46 [get_ports c0_ddr4_ck_t[0]]
#set_property PACKAGE_PIN BK41 [get_ports c0_ddr4_ck_c[1]]
#set_property PACKAGE_PIN BJ41 [get_ports c0_ddr4_ck_t[1]]
set_property PACKAGE_PIN BH42 [get_ports c0_ddr4_cke[0]]
#set_property PACKAGE_PIN BJ42 [get_ports c0_ddr4_cke[1]]
set_property PACKAGE_PIN BK46 [get_ports c0_ddr4_cs_n[0]]
# PROHIBIT ON THIS?
#set_property PACKAGE_PIN BE45 [get_ports c0_ddr4_cs_n[1]]
#set_property PACKAGE_PIN BJ43 [get_ports c0_ddr4_cs_n[2]]
#set_property PACKAGE_PIN BJ44 [get_ports c0_ddr4_cs_n[3]]
set_property PACKAGE_PIN BN32 [get_ports c0_ddr4_dq[0]]
set_property PACKAGE_PIN BP32 [get_ports c0_ddr4_dq[1]]
set_property PACKAGE_PIN BL30 [get_ports c0_ddr4_dq[2]]
set_property PACKAGE_PIN BM30 [get_ports c0_ddr4_dq[3]]
set_property PACKAGE_PIN BP29 [get_ports c0_ddr4_dq[4]]
set_property PACKAGE_PIN BP28 [get_ports c0_ddr4_dq[5]]
set_property PACKAGE_PIN BP31 [get_ports c0_ddr4_dq[6]]
set_property PACKAGE_PIN BN31 [get_ports c0_ddr4_dq[7]]
set_property PACKAGE_PIN BJ31 [get_ports c0_ddr4_dq[8]]
set_property PACKAGE_PIN BH31 [get_ports c0_ddr4_dq[9]]
set_property PACKAGE_PIN BF32 [get_ports c0_ddr4_dq[10]]
set_property PACKAGE_PIN BF33 [get_ports c0_ddr4_dq[11]]
set_property PACKAGE_PIN BH29 [get_ports c0_ddr4_dq[12]]
set_property PACKAGE_PIN BH30 [get_ports c0_ddr4_dq[13]]
set_property PACKAGE_PIN BF31 [get_ports c0_ddr4_dq[14]]
set_property PACKAGE_PIN BG32 [get_ports c0_ddr4_dq[15]]
set_property PACKAGE_PIN BK31 [get_ports c0_ddr4_dq[16]]
set_property PACKAGE_PIN BL31 [get_ports c0_ddr4_dq[17]]
set_property PACKAGE_PIN BK33 [get_ports c0_ddr4_dq[18]]
set_property PACKAGE_PIN BL33 [get_ports c0_ddr4_dq[19]]
set_property PACKAGE_PIN BL32 [get_ports c0_ddr4_dq[20]]
set_property PACKAGE_PIN BM33 [get_ports c0_ddr4_dq[21]]
set_property PACKAGE_PIN BN34 [get_ports c0_ddr4_dq[22]]
set_property PACKAGE_PIN BP34 [get_ports c0_ddr4_dq[23]]
set_property PACKAGE_PIN BH34 [get_ports c0_ddr4_dq[24]]
set_property PACKAGE_PIN BH35 [get_ports c0_ddr4_dq[25]]
set_property PACKAGE_PIN BF35 [get_ports c0_ddr4_dq[26]]
set_property PACKAGE_PIN BF36 [get_ports c0_ddr4_dq[27]]
set_property PACKAGE_PIN BJ33 [get_ports c0_ddr4_dq[28]]
set_property PACKAGE_PIN BJ34 [get_ports c0_ddr4_dq[29]]
set_property PACKAGE_PIN BG34 [get_ports c0_ddr4_dq[30]]
set_property PACKAGE_PIN BG35 [get_ports c0_ddr4_dq[31]]
set_property PACKAGE_PIN BM52 [get_ports c0_ddr4_dq[32]]
set_property PACKAGE_PIN BL53 [get_ports c0_ddr4_dq[33]]
set_property PACKAGE_PIN BL52 [get_ports c0_ddr4_dq[34]]
set_property PACKAGE_PIN BL51 [get_ports c0_ddr4_dq[35]]
set_property PACKAGE_PIN BN50 [get_ports c0_ddr4_dq[36]]
set_property PACKAGE_PIN BN51 [get_ports c0_ddr4_dq[37]]
set_property PACKAGE_PIN BN49 [get_ports c0_ddr4_dq[38]]
set_property PACKAGE_PIN BM48 [get_ports c0_ddr4_dq[39]]
set_property PACKAGE_PIN BE50 [get_ports c0_ddr4_dq[40]]
set_property PACKAGE_PIN BE49 [get_ports c0_ddr4_dq[41]]
set_property PACKAGE_PIN BE51 [get_ports c0_ddr4_dq[42]]
set_property PACKAGE_PIN BD51 [get_ports c0_ddr4_dq[43]]
set_property PACKAGE_PIN BF52 [get_ports c0_ddr4_dq[44]]
set_property PACKAGE_PIN BF51 [get_ports c0_ddr4_dq[45]]
set_property PACKAGE_PIN BG50 [get_ports c0_ddr4_dq[46]]
set_property PACKAGE_PIN BF50 [get_ports c0_ddr4_dq[47]]
set_property PACKAGE_PIN BH50 [get_ports c0_ddr4_dq[48]]
set_property PACKAGE_PIN BJ51 [get_ports c0_ddr4_dq[49]]
set_property PACKAGE_PIN BH51 [get_ports c0_ddr4_dq[50]]
set_property PACKAGE_PIN BH49 [get_ports c0_ddr4_dq[51]]
set_property PACKAGE_PIN BK50 [get_ports c0_ddr4_dq[52]]
set_property PACKAGE_PIN BK51 [get_ports c0_ddr4_dq[53]]
set_property PACKAGE_PIN BJ49 [get_ports c0_ddr4_dq[54]]
set_property PACKAGE_PIN BJ48 [get_ports c0_ddr4_dq[55]]
set_property PACKAGE_PIN BN44 [get_ports c0_ddr4_dq[56]]
set_property PACKAGE_PIN BN45 [get_ports c0_ddr4_dq[57]]
set_property PACKAGE_PIN BM44 [get_ports c0_ddr4_dq[58]]
set_property PACKAGE_PIN BM45 [get_ports c0_ddr4_dq[59]]
set_property PACKAGE_PIN BP43 [get_ports c0_ddr4_dq[60]]
set_property PACKAGE_PIN BP44 [get_ports c0_ddr4_dq[61]]
set_property PACKAGE_PIN BN47 [get_ports c0_ddr4_dq[62]]
set_property PACKAGE_PIN BP47 [get_ports c0_ddr4_dq[63]]
set_property PACKAGE_PIN BG54 [get_ports c0_ddr4_dq[64]]
set_property PACKAGE_PIN BG53 [get_ports c0_ddr4_dq[65]]
set_property PACKAGE_PIN BE53 [get_ports c0_ddr4_dq[66]]
set_property PACKAGE_PIN BE54 [get_ports c0_ddr4_dq[67]]
set_property PACKAGE_PIN BH52 [get_ports c0_ddr4_dq[68]]
set_property PACKAGE_PIN BG52 [get_ports c0_ddr4_dq[69]]
set_property PACKAGE_PIN BK54 [get_ports c0_ddr4_dq[70]]
set_property PACKAGE_PIN BK53 [get_ports c0_ddr4_dq[71]]
set_property PACKAGE_PIN BN30 [get_ports c0_ddr4_dqs_c[0]]
set_property PACKAGE_PIN BN29 [get_ports c0_ddr4_dqs_t[0]]
set_property PACKAGE_PIN BM29 [get_ports c0_ddr4_dqs_c[1]]
set_property PACKAGE_PIN BM28 [get_ports c0_ddr4_dqs_t[1]]
set_property PACKAGE_PIN BK30 [get_ports c0_ddr4_dqs_c[2]]
set_property PACKAGE_PIN BJ29 [get_ports c0_ddr4_dqs_t[2]]
set_property PACKAGE_PIN BG30 [get_ports c0_ddr4_dqs_c[3]]
set_property PACKAGE_PIN BG29 [get_ports c0_ddr4_dqs_t[3]]
set_property PACKAGE_PIN BM35 [get_ports c0_ddr4_dqs_c[4]]
set_property PACKAGE_PIN BL35 [get_ports c0_ddr4_dqs_t[4]]
set_property PACKAGE_PIN BN35 [get_ports c0_ddr4_dqs_c[5]]
set_property PACKAGE_PIN BM34 [get_ports c0_ddr4_dqs_t[5]]
set_property PACKAGE_PIN BK35 [get_ports c0_ddr4_dqs_c[6]]
set_property PACKAGE_PIN BK34 [get_ports c0_ddr4_dqs_t[6]]
set_property PACKAGE_PIN BJ32 [get_ports c0_ddr4_dqs_c[7]]
set_property PACKAGE_PIN BH32 [get_ports c0_ddr4_dqs_t[7]]
set_property PACKAGE_PIN BM50 [get_ports c0_ddr4_dqs_c[8]]
set_property PACKAGE_PIN BM49 [get_ports c0_ddr4_dqs_t[8]]
set_property PACKAGE_PIN BP49 [get_ports c0_ddr4_dqs_c[9]]
set_property PACKAGE_PIN BP48 [get_ports c0_ddr4_dqs_t[9]]
set_property PACKAGE_PIN BF48 [get_ports c0_ddr4_dqs_c[10]]
set_property PACKAGE_PIN BF47 [get_ports c0_ddr4_dqs_t[10]]
set_property PACKAGE_PIN BG49 [get_ports c0_ddr4_dqs_c[11]]
set_property PACKAGE_PIN BG48 [get_ports c0_ddr4_dqs_t[11]]
set_property PACKAGE_PIN BJ47 [get_ports c0_ddr4_dqs_c[12]]
set_property PACKAGE_PIN BH47 [get_ports c0_ddr4_dqs_t[12]]
set_property PACKAGE_PIN BK49 [get_ports c0_ddr4_dqs_c[13]]
set_property PACKAGE_PIN BK48 [get_ports c0_ddr4_dqs_t[13]]
set_property PACKAGE_PIN BP46 [get_ports c0_ddr4_dqs_c[14]]
set_property PACKAGE_PIN BN46 [get_ports c0_ddr4_dqs_t[14]]
set_property PACKAGE_PIN BP42 [get_ports c0_ddr4_dqs_c[15]]
set_property PACKAGE_PIN BN42 [get_ports c0_ddr4_dqs_t[15]]
set_property PACKAGE_PIN BJ54 [get_ports c0_ddr4_dqs_c[16]]
set_property PACKAGE_PIN BH54 [get_ports c0_ddr4_dqs_t[16]]
set_property PACKAGE_PIN BJ53 [get_ports c0_ddr4_dqs_c[17]]
set_property PACKAGE_PIN BJ52 [get_ports c0_ddr4_dqs_t[17]]
set_property PACKAGE_PIN BG44 [get_ports c0_ddr4_odt[0]]
#set_property PACKAGE_PIN BE46 [get_ports c0_ddr4_odt[1]]
set_property PACKAGE_PIN BG33 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN BF45 [get_ports c0_ddr4_par]
set_property PACKAGE_PIN BG3 [get_ports c1_ddr4_act_n]
set_property PACKAGE_PIN BF7 [get_ports c1_ddr4_adr[0]]
set_property PACKAGE_PIN BK1 [get_ports c1_ddr4_adr[1]]
set_property PACKAGE_PIN BF6 [get_ports c1_ddr4_adr[2]]
set_property PACKAGE_PIN BF5 [get_ports c1_ddr4_adr[3]]
set_property PACKAGE_PIN BE3 [get_ports c1_ddr4_adr[4]]
set_property PACKAGE_PIN BE6 [get_ports c1_ddr4_adr[5]]
set_property PACKAGE_PIN BE5 [get_ports c1_ddr4_adr[6]]
set_property PACKAGE_PIN BG7 [get_ports c1_ddr4_adr[7]]
set_property PACKAGE_PIN BJ1 [get_ports c1_ddr4_adr[8]]
set_property PACKAGE_PIN BG2 [get_ports c1_ddr4_adr[9]]
set_property PACKAGE_PIN BJ8 [get_ports c1_ddr4_adr[10]]
set_property PACKAGE_PIN BE4 [get_ports c1_ddr4_adr[11]]
set_property PACKAGE_PIN BL2 [get_ports c1_ddr4_adr[12]]
set_property PACKAGE_PIN BK5 [get_ports c1_ddr4_adr[13]]
set_property PACKAGE_PIN BK8 [get_ports c1_ddr4_adr[14]]
set_property PACKAGE_PIN BJ4 [get_ports c1_ddr4_adr[15]]
set_property PACKAGE_PIN BF8 [get_ports c1_ddr4_adr[16]]
set_property PACKAGE_PIN BG8 [get_ports c1_ddr4_ba[0]]
set_property PACKAGE_PIN BK4 [get_ports c1_ddr4_ba[1]]
set_property PACKAGE_PIN BF3 [get_ports c1_ddr4_bg[0]]
set_property PACKAGE_PIN BF2 [get_ports c1_ddr4_bg[1]]
set_property PACKAGE_PIN BJ2 [get_ports c1_ddr4_ck_c[0]]
set_property PACKAGE_PIN BJ3 [get_ports c1_ddr4_ck_t[0]]
#set_property PACKAGE_PIN BJ7 [get_ports c1_ddr4_ck_c[1]]
#set_property PACKAGE_PIN BH7 [get_ports c1_ddr4_ck_t[1]]
set_property PACKAGE_PIN BE1 [get_ports c1_ddr4_cke[0]]
#set_property PACKAGE_PIN BF1 [get_ports c1_ddr4_cke[1]]
set_property PACKAGE_PIN BL3 [get_ports c1_ddr4_cs_n[0]]
#set_property PACKAGE_PIN BH5 [get_ports c1_ddr4_cs1_n]
#set_property PACKAGE_PIN BG5 [get_ports c1_ddr4_cs2_n]
#set_property PACKAGE_PIN BG4 [get_ports c1_ddr4_cs3_n]
set_property PACKAGE_PIN A11 [get_ports c1_ddr4_dq[0]]
set_property PACKAGE_PIN A10 [get_ports c1_ddr4_dq[1]]
set_property PACKAGE_PIN A9 [get_ports c1_ddr4_dq[2]]
set_property PACKAGE_PIN A8 [get_ports c1_ddr4_dq[3]]
set_property PACKAGE_PIN B12 [get_ports c1_ddr4_dq[4]]
set_property PACKAGE_PIN B10 [get_ports c1_ddr4_dq[5]]
set_property PACKAGE_PIN C12 [get_ports c1_ddr4_dq[6]]
set_property PACKAGE_PIN B11 [get_ports c1_ddr4_dq[7]]
set_property PACKAGE_PIN E11 [get_ports c1_ddr4_dq[8]]
set_property PACKAGE_PIN D11 [get_ports c1_ddr4_dq[9]]
set_property PACKAGE_PIN E12 [get_ports c1_ddr4_dq[10]]
set_property PACKAGE_PIN F11 [get_ports c1_ddr4_dq[11]]
set_property PACKAGE_PIN F10 [get_ports c1_ddr4_dq[12]]
set_property PACKAGE_PIN E9 [get_ports c1_ddr4_dq[13]]
set_property PACKAGE_PIN F9 [get_ports c1_ddr4_dq[14]]
set_property PACKAGE_PIN G11 [get_ports c1_ddr4_dq[15]]
set_property PACKAGE_PIN H12 [get_ports c1_ddr4_dq[16]]
set_property PACKAGE_PIN G13 [get_ports c1_ddr4_dq[17]]
set_property PACKAGE_PIN H13 [get_ports c1_ddr4_dq[18]]
set_property PACKAGE_PIN H14 [get_ports c1_ddr4_dq[19]]
set_property PACKAGE_PIN J11 [get_ports c1_ddr4_dq[20]]
set_property PACKAGE_PIN J12 [get_ports c1_ddr4_dq[21]]
set_property PACKAGE_PIN J15 [get_ports c1_ddr4_dq[22]]
set_property PACKAGE_PIN J14 [get_ports c1_ddr4_dq[23]]
set_property PACKAGE_PIN A14 [get_ports c1_ddr4_dq[24]]
set_property PACKAGE_PIN C15 [get_ports c1_ddr4_dq[25]]
set_property PACKAGE_PIN A15 [get_ports c1_ddr4_dq[26]]
set_property PACKAGE_PIN B15 [get_ports c1_ddr4_dq[27]]
set_property PACKAGE_PIN F15 [get_ports c1_ddr4_dq[28]]
set_property PACKAGE_PIN E14 [get_ports c1_ddr4_dq[29]]
set_property PACKAGE_PIN F14 [get_ports c1_ddr4_dq[30]]
set_property PACKAGE_PIN F13 [get_ports c1_ddr4_dq[31]]
set_property PACKAGE_PIN BM3 [get_ports c1_ddr4_dq[32]]
set_property PACKAGE_PIN BM4 [get_ports c1_ddr4_dq[33]]
set_property PACKAGE_PIN BM5 [get_ports c1_ddr4_dq[34]]
set_property PACKAGE_PIN BL6 [get_ports c1_ddr4_dq[35]]
set_property PACKAGE_PIN BN4 [get_ports c1_ddr4_dq[36]]
set_property PACKAGE_PIN BN5 [get_ports c1_ddr4_dq[37]]
set_property PACKAGE_PIN BN6 [get_ports c1_ddr4_dq[38]]
set_property PACKAGE_PIN BN7 [get_ports c1_ddr4_dq[39]]
set_property PACKAGE_PIN BJ9 [get_ports c1_ddr4_dq[40]]
set_property PACKAGE_PIN BK9 [get_ports c1_ddr4_dq[41]]
set_property PACKAGE_PIN BK10 [get_ports c1_ddr4_dq[42]]
set_property PACKAGE_PIN BL10 [get_ports c1_ddr4_dq[43]]
set_property PACKAGE_PIN BM9 [get_ports c1_ddr4_dq[44]]
set_property PACKAGE_PIN BN9 [get_ports c1_ddr4_dq[45]]
set_property PACKAGE_PIN BN10 [get_ports c1_ddr4_dq[46]]
set_property PACKAGE_PIN BM10 [get_ports c1_ddr4_dq[47]]
set_property PACKAGE_PIN BM15 [get_ports c1_ddr4_dq[48]]
set_property PACKAGE_PIN BM14 [get_ports c1_ddr4_dq[49]]
set_property PACKAGE_PIN BL15 [get_ports c1_ddr4_dq[50]]
set_property PACKAGE_PIN BM13 [get_ports c1_ddr4_dq[51]]
set_property PACKAGE_PIN BN12 [get_ports c1_ddr4_dq[52]]
set_property PACKAGE_PIN BM12 [get_ports c1_ddr4_dq[53]]
set_property PACKAGE_PIN BP13 [get_ports c1_ddr4_dq[54]]
set_property PACKAGE_PIN BP14 [get_ports c1_ddr4_dq[55]]
set_property PACKAGE_PIN BJ13 [get_ports c1_ddr4_dq[56]]
set_property PACKAGE_PIN BJ12 [get_ports c1_ddr4_dq[57]]
set_property PACKAGE_PIN BH15 [get_ports c1_ddr4_dq[58]]
set_property PACKAGE_PIN BH14 [get_ports c1_ddr4_dq[59]]
set_property PACKAGE_PIN BK14 [get_ports c1_ddr4_dq[60]]
set_property PACKAGE_PIN BK15 [get_ports c1_ddr4_dq[61]]
set_property PACKAGE_PIN BL12 [get_ports c1_ddr4_dq[62]]
set_property PACKAGE_PIN BL13 [get_ports c1_ddr4_dq[63]]
set_property PACKAGE_PIN BE9 [get_ports c1_ddr4_dq[64]]
set_property PACKAGE_PIN BE10 [get_ports c1_ddr4_dq[65]]
set_property PACKAGE_PIN BF10 [get_ports c1_ddr4_dq[66]]
set_property PACKAGE_PIN BE11 [get_ports c1_ddr4_dq[67]]
set_property PACKAGE_PIN BG13 [get_ports c1_ddr4_dq[68]]
set_property PACKAGE_PIN BG12 [get_ports c1_ddr4_dq[69]]
set_property PACKAGE_PIN BG9 [get_ports c1_ddr4_dq[70]]
set_property PACKAGE_PIN BG10 [get_ports c1_ddr4_dq[71]]
set_property PACKAGE_PIN A13 [get_ports c1_ddr4_dqs_c[0]]
set_property PACKAGE_PIN B13 [get_ports c1_ddr4_dqs_t[0]]
set_property PACKAGE_PIN C9 [get_ports c1_ddr4_dqs_c[1]]
set_property PACKAGE_PIN C10 [get_ports c1_ddr4_dqs_t[1]]
set_property PACKAGE_PIN D9 [get_ports c1_ddr4_dqs_c[2]]
set_property PACKAGE_PIN D10 [get_ports c1_ddr4_dqs_t[2]]
set_property PACKAGE_PIN G10 [get_ports c1_ddr4_dqs_c[3]]
set_property PACKAGE_PIN H10 [get_ports c1_ddr4_dqs_t[3]]
set_property PACKAGE_PIN G15 [get_ports c1_ddr4_dqs_c[4]]
set_property PACKAGE_PIN H15 [get_ports c1_ddr4_dqs_t[4]]
set_property PACKAGE_PIN K13 [get_ports c1_ddr4_dqs_c[5]]
set_property PACKAGE_PIN K14 [get_ports c1_ddr4_dqs_t[5]]
set_property PACKAGE_PIN D14 [get_ports c1_ddr4_dqs_c[6]]
set_property PACKAGE_PIN D15 [get_ports c1_ddr4_dqs_t[6]]
set_property PACKAGE_PIN D12 [get_ports c1_ddr4_dqs_c[7]]
set_property PACKAGE_PIN E13 [get_ports c1_ddr4_dqs_t[7]]
set_property PACKAGE_PIN BM7 [get_ports c1_ddr4_dqs_c[8]]
set_property PACKAGE_PIN BL7 [get_ports c1_ddr4_dqs_t[8]]
set_property PACKAGE_PIN BP6 [get_ports c1_ddr4_dqs_c[9]]
set_property PACKAGE_PIN BP7 [get_ports c1_ddr4_dqs_t[9]]
set_property PACKAGE_PIN BM8 [get_ports c1_ddr4_dqs_c[10]]
set_property PACKAGE_PIN BL8 [get_ports c1_ddr4_dqs_t[10]]
set_property PACKAGE_PIN BP8 [get_ports c1_ddr4_dqs_c[11]]
set_property PACKAGE_PIN BP9 [get_ports c1_ddr4_dqs_t[11]]
set_property PACKAGE_PIN BN14 [get_ports c1_ddr4_dqs_c[12]]
set_property PACKAGE_PIN BN15 [get_ports c1_ddr4_dqs_t[12]]
set_property PACKAGE_PIN BP11 [get_ports c1_ddr4_dqs_c[13]]
set_property PACKAGE_PIN BP12 [get_ports c1_ddr4_dqs_t[13]]
set_property PACKAGE_PIN BK13 [get_ports c1_ddr4_dqs_c[14]]
set_property PACKAGE_PIN BJ14 [get_ports c1_ddr4_dqs_t[14]]
set_property PACKAGE_PIN BK11 [get_ports c1_ddr4_dqs_c[15]]
set_property PACKAGE_PIN BJ11 [get_ports c1_ddr4_dqs_t[15]]
set_property PACKAGE_PIN BF11 [get_ports c1_ddr4_dqs_c[16]]
set_property PACKAGE_PIN BF12 [get_ports c1_ddr4_dqs_t[16]]
set_property PACKAGE_PIN BH9 [get_ports c1_ddr4_dqs_c[17]]
set_property PACKAGE_PIN BH10 [get_ports c1_ddr4_dqs_t[17]]
set_property PACKAGE_PIN BH2 [get_ports c1_ddr4_odt[0]]
#set_property PACKAGE_PIN BH4 [get_ports c1_ddr4_odt[1]]
set_property PACKAGE_PIN BH12 [get_ports c1_ddr4_reset_n]
set_property PACKAGE_PIN BH1 [get_ports c1_ddr4_par]

# Don't insert buffers
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_p[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_p[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_n[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_p[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_n[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_p[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_n[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_p[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_n[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_p[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_n[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_gtx_p[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_n[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_00_grx_p[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_p[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_p[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_n[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_p[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_n[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_p[1]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_n[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_p[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_n[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_p[2]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_n[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_gtx_p[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_n[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_gt_gtyquad_01_grx_p[3]}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk0_00_clk_n}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk0_00_clk_p}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk1_00_clk_n}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk1_00_clk_p}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk0_01_clk_n}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk0_01_clk_p}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk1_01_clk_n}]
set_property IO_BUFFER_TYPE NONE [get_ports {io_clk_gtyquad_refclk1_01_clk_p}]
